# Form implementation generated from reading ui file 'grafana.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt6.QtWidgets import QTableWidgetItem, QMessageBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1185, 855)
        Form.setStyleSheet("background-color:rgb(44, 50, 53);")
        self.label_icon = QtWidgets.QLabel(parent=Form)
        self.label_icon.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.label_icon.setStyleSheet("border-image:url(\"C:/Users/82105/Desktop/grafana_icon\")")
        self.label_icon.setText("")
        self.label_icon.setObjectName("label_icon")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(50, 60, 1081, 731))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_du_id = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_du_id.setFont(font)
        self.label_du_id.setStyleSheet("color: rgb(52, 162, 230);\n"
                                       "background-color:rgb(32, 34, 38);")
        self.label_du_id.setObjectName("label_du_id")
        self.verticalLayout.addWidget(self.label_du_id)
        self.label_du_name = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_du_name.setFont(font)
        self.label_du_name.setStyleSheet("color: rgb(52, 162, 230);\n"
                                         "background-color:rgb(32, 34, 38);")
        self.label_du_name.setObjectName("label_du_name")
        self.verticalLayout.addWidget(self.label_du_name)
        self.label_ru_name = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_ru_name.setFont(font)
        self.label_ru_name.setStyleSheet("color: rgb(52, 162, 230);\n"
                                         "background-color:rgb(32, 34, 38);")
        self.label_ru_name.setObjectName("label_ru_name")
        self.verticalLayout.addWidget(self.label_ru_name)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_du_id = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_du_id.setFont(font)
        self.lineEdit_du_id.setStyleSheet("color: rgb(255, 255, 255);\n"
                                          "background-color:rgb(32, 34, 38);")
        self.lineEdit_du_id.setObjectName("lineEdit_du_id")
        self.verticalLayout_2.addWidget(self.lineEdit_du_id)
        self.lineEdit_du_name = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_du_name.setFont(font)
        self.lineEdit_du_name.setStyleSheet("color: rgb(255, 255, 255);\n"
                                            "background-color:rgb(32, 34, 38);")
        self.lineEdit_du_name.setObjectName("lineEdit_du_name")
        self.verticalLayout_2.addWidget(self.lineEdit_du_name)
        self.lineEdit_ru_name = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_ru_name.setFont(font)
        self.lineEdit_ru_name.setStyleSheet("color: rgb(255, 255, 255);\n"
                                            "background-color:rgb(32, 34, 38);")
        self.lineEdit_ru_name.setText("")
        self.lineEdit_ru_name.setObjectName("lineEdit_ru_name")
        self.verticalLayout_2.addWidget(self.lineEdit_ru_name)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color:rgb(32, 34, 38);")
        self.tableWidget.setLineWidth(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.verticalLayout_4.addWidget(self.tableWidget)

        # 테이블 초기화 코드
        self.tableWidget.setStyleSheet(
            "QTableWidget QHeaderView::section {"
            "background-color: rgb(32, 34, 38);"
            "color: rgb(52, 162, 230);"
            "}"
        )

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.select_data() # 처음 실행 시 데이터를 불러온다.

        # 텍스트 변경 이벤트 처리
        self.lineEdit_du_id.textChanged.connect(self.filter_data)
        self.lineEdit_du_name.textChanged.connect(self.filter_data)
        self.lineEdit_ru_name.textChanged.connect(self.filter_data)

        Form.setWindowTitle("승우의 Grafana")

    def select_data(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="apple"
            )

            cursor = mydb.cursor()
            cursor.execute("SELECT * FROM tf_task")
            result = cursor.fetchall()

            # 테이블에 데이터 추가
            self.tableWidget.setRowCount(len(result))
            for i, row in enumerate(result):
                for j, col in enumerate(row):
                    item = QtWidgets.QTableWidgetItem(str(col))
                    item.setForeground(QtGui.QColor(255, 255, 255))
                    self.tableWidget.setItem(i, j, item)

        except mc.Error as e:
            QMessageBox.about(self, "에러 발생", "DB에 연결 실패")

    def filter_data(self):
        filter_du_id = self.lineEdit_du_id.text()
        filter_du_name = self.lineEdit_du_name.text()
        filter_ru_name = self.lineEdit_ru_name.text()

        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="apple"
            )

            cursor = mydb.cursor()
            # 입력된 값으로 필터링
            cursor.execute("SELECT * FROM tf_task WHERE du_id LIKE %s AND du_name LIKE %s AND ru_name LIKE %s",
                           ('%' + filter_du_id + '%', '%' + filter_du_name + '%', '%' + filter_ru_name + '%'))
            result = cursor.fetchall()

            # 테이블 초기화
            self.tableWidget.setRowCount(0)

            # 필터링된 데이터를 테이블에 추가
            for i, row in enumerate(result):
                self.tableWidget.insertRow(i)
                for j, col in enumerate(row):
                    item = QtWidgets.QTableWidgetItem(str(col))
                    item.setForeground(QtGui.QColor(255, 255, 255))
                    self.tableWidget.setItem(i, j, item)

        except mc.Error as e:
            QMessageBox.about(self, "에러 발생", "DB에 연결 실패")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_du_id.setText(_translate("Form", "du_id"))
        self.label_du_name.setText(_translate("Form", "du_name"))
        self.label_ru_name.setText(_translate("Form", "ru_name"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "index"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "location"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "du_id"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "du_name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "ru_name"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "pci"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "cell_info"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())