# Form implementation generated from reading ui file 'DB_practice.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#  pyuic6 -x DB_practice.ui -o DB_practice.py 이 명령어를 통해 ui파일을 py로 변환

from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_createdb = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_createdb.setFont(font)
        self.pushButton_createdb.setObjectName("pushButton_createdb")
        # 푸시버튼과 DB생성 연결하기
        self.pushButton_createdb.clicked.connect(self.create_database)
        self.horizontalLayout_2.addWidget(self.pushButton_createdb)
        self.pushButton_dbcon = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_dbcon.setFont(font)
        self.pushButton_dbcon.setObjectName("pushButton_dbcon")
        # 푸시버튼과 DB연결 연결하기
        self.pushButton_dbcon.clicked.connect(self.db_connect)
        self.horizontalLayout_2.addWidget(self.pushButton_dbcon)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_result = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def create_database(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password=""
            )

            cursor = mydb.cursor()
            dbname = self.lineEdit.text()

            cursor.execute(f'DB 생성 {dbname}')
            self.label_result.setText(f'DB {dbname} 생성')

        except mc.Error as e:
            self.label_result.setText("DB 생성 실패")

    def db_connect(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                pasword="",
                database="apple"
            )

            self.label_result.setText("연결 완료")

        except mc.Error as e:
            self.label_result.setText("연결 실패")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "데이터베이스 name"))
        self.pushButton_createdb.setText(_translate("Form", "DB 생성"))
        self.pushButton_dbcon.setText(_translate("Form", "DB 연결"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
