from PyQt6 import QtCore, QtGui, QtWidgets


class DetailsWindow(QtWidgets.QWidget):
    def __init__(self, data):
        super().__init__()
        self.data = data
        self.setupUi(self) # UI 초기화 함수 호출
        self.setWindowTitle(data[4])
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 450)
        Form.setStyleSheet("background-color:rgb(22, 23, 25);")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(380, 150, 95, 72))
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_cell_lock = QtWidgets.QCheckBox(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_cell_lock.setFont(font)
        self.checkBox_cell_lock.setStyleSheet("background-color:rgb(33, 35, 39); color: rgb(255, 255, 255);")
        self.checkBox_cell_lock.setObjectName("checkBox_cell_lock")
        self.verticalLayout_7.addWidget(self.checkBox_cell_lock)
        self.pushButton_reset = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setStyleSheet("background-color:rgb(33, 35, 39); color: rgb(255, 255, 255);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_7.addWidget(self.pushButton_reset)
        self.widget1 = QtWidgets.QWidget(parent=Form)
        self.widget1.setGeometry(QtCore.QRect(30, 40, 269, 109))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_pci = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_pci.setFont(font)
        self.label_pci.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_pci.setStyleSheet("background-color:rgb(33, 35, 39); color: rgb(255, 255, 255);")
        self.label_pci.setObjectName("label_pci")
        self.verticalLayout.addWidget(self.label_pci)
        self.label_cell_info = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_cell_info.setFont(font)
        self.label_cell_info.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_cell_info.setStyleSheet("background-color:rgb(33, 35, 39); color: rgb(255, 255, 255);")
        self.label_cell_info.setObjectName("label_cell_info")
        self.verticalLayout.addWidget(self.label_cell_info)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.label_type = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_type.setFont(font)
        self.label_type.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_type.setStyleSheet("background-color:rgb(33, 35, 39); color: rgb(255, 255, 255);")
        self.label_type.setObjectName("label_type")
        self.verticalLayout_4.addWidget(self.label_type)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_pci = QtWidgets.QLineEdit(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_pci.setFont(font)
        self.lineEdit_pci.setStyleSheet("background-color:rgb(9, 9, 11);  color: rgb(255, 255, 255);")
        self.lineEdit_pci.setText(self.data[5])
        self.lineEdit_pci.setObjectName("lineEdit_pci")
        self.lineEdit_pci.setReadOnly(True)
        self.verticalLayout_9.addWidget(self.lineEdit_pci)
        self.lineEdit_cell_info = QtWidgets.QLineEdit(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_cell_info.setFont(font)
        self.lineEdit_cell_info.setStyleSheet("background-color:rgb(9, 9, 11); color: rgb(255, 255, 255);")
        self.lineEdit_cell_info.setText(self.data[6])
        self.lineEdit_cell_info.setObjectName("lineEdit_cell_info")
        self.lineEdit_cell_info.setReadOnly(True)
        self.verticalLayout_9.addWidget(self.lineEdit_cell_info)
        self.lineEdit_type = QtWidgets.QLineEdit(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_type.setFont(font)
        self.lineEdit_type.setStyleSheet("background-color:rgb(9, 9, 11); color: rgb(255, 255, 255);")
        self.lineEdit_type.setText(self.data[7])
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.lineEdit_type.setReadOnly(True)
        self.verticalLayout_9.addWidget(self.lineEdit_type)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.widget2 = QtWidgets.QWidget(parent=Form)
        self.widget2.setGeometry(QtCore.QRect(30, 210, 271, 109))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_output = QtWidgets.QLabel(parent=self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_output.setFont(font)
        self.label_output.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_output.setStyleSheet("background-color:rgb(33, 35, 39); color: rgb(255, 255, 255);")
        self.label_output.setObjectName("label_output")
        self.verticalLayout_3.addWidget(self.label_output)
        self.label_vswr = QtWidgets.QLabel(parent=self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_vswr.setFont(font)
        self.label_vswr.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_vswr.setStyleSheet("background-color:rgb(33, 35, 39); color: rgb(255, 255, 255);")
        self.label_vswr.setObjectName("label_vswr")
        self.verticalLayout_3.addWidget(self.label_vswr)
        self.label_rssi = QtWidgets.QLabel(parent=self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_rssi.setFont(font)
        self.label_rssi.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_rssi.setStyleSheet("background-color:rgb(33, 35, 39); color: rgb(255, 255, 255);")
        self.label_rssi.setObjectName("label_rssi")
        self.verticalLayout_3.addWidget(self.label_rssi)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_output = QtWidgets.QLineEdit(parent=self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_output.setFont(font)
        self.lineEdit_output.setStyleSheet("background-color:rgb(9, 9, 11); color: rgb(255, 255, 255);")
        self.lineEdit_output.setText(self.data[8])
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.lineEdit_output.setReadOnly(True)
        self.verticalLayout_6.addWidget(self.lineEdit_output)
        self.lineEdit_vswr = QtWidgets.QLineEdit(parent=self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_vswr.setFont(font)
        self.lineEdit_vswr.setStyleSheet("background-color:rgb(9, 9, 11); color: rgb(255, 255, 255);")
        self.lineEdit_vswr.setText(self.data[9])
        self.lineEdit_vswr.setObjectName("lineEdit_vswr")
        self.lineEdit_vswr.setReadOnly(True)
        self.verticalLayout_6.addWidget(self.lineEdit_vswr)
        self.lineEdit_rssi = QtWidgets.QLineEdit(parent=self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_rssi.setFont(font)
        self.lineEdit_rssi.setStyleSheet("background-color:rgb(9, 9, 11); color: rgb(255, 255, 255);")
        self.lineEdit_rssi.setText(self.data[10])
        self.lineEdit_rssi.setObjectName("lineEdit_rssi")
        self.lineEdit_rssi.setReadOnly(True)
        self.verticalLayout_6.addWidget(self.lineEdit_rssi)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_cell_lock.setText(_translate("Form", "cell lock"))
        self.pushButton_reset.setText(_translate("Form", "reset"))
        self.label_pci.setText(_translate("Form", "pci"))
        self.label_cell_info.setText(_translate("Form", "cell_info"))
        self.label_type.setText(_translate("Form", "type"))
        self.label_output.setText(_translate("Form", "출력"))
        self.label_vswr.setText(_translate("Form", "정재파비"))
        self.label_rssi.setText(_translate("Form", "RSSI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = DetailsWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
